name: test
on:
  push:
    branches: [ test-codecov ]
  pull_request:
    branches: [ test-codecov ]
jobs:
  ci-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        go: [ 1.12, 1.13, 1.14 ]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Set up golang with version ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Run tests
        run: go test -v -coverprofile=covprofile ./...
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: shovelwagon/opsgenie-go-sdk-v2
          file: covprofile
